### ISSUE TITLE
Setup instructions on How It Works page is broken

### ISSUE THREAD

**Issue by pzelnip** [dashbird/site#2]
Going to https://dashbird.io/help/basics/how-it-works/ and clicking the "You can find setup instructions here." link results in:

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: getting-started/setting-up-dashbird
RequestId: FB5B6D55700F0282
HostId: 83jIidFd432uSSFcGU8KxmRq0SxqFeh1YgmrImfPfHIljfDe7pIi3n1PFzSDgBXT6+6idrfRVEs=
```

**Comment by taavirehemagi** [comment]
Hey @pzelnip, thanks for letting us know.

I just fixed the link and deployed it.
Actually, I'll move the KB over to the new design some time next week.
