### ISSUE TITLE
Site Loading speed is very Low

### ISSUE THREAD

**Issue by saigowthamr** [dashbird/site#45]
1. 1.8mb  is consumed to download only images.
![](https://i.imgur.com/nYfAXSK.png)
 Use CDN to host your images or Compress images because browser only allows 6 requests per host at a time.

2. Remove the unused CSS.

**Comment by adnanrahic** [comment]
Hey Sai!

Awesome of you noticing. We've fixed the issues and the site is as quick as it can get.
Feel free to check it out!

Cheers! :smile:

**Comment by saigowthamr** [comment]
doument.wirte() is not recommended
![](https://i.imgur.com/MyhFCkG.png)

There are some accessibility issues like alt attributes are  missing 
![](https://i.imgur.com/Ap1KYFy.png)



Use Preconnect to resolve the DNS and TCP/TLS handshaking.

example:  <link rel="preconnect" href="https://cdnjs.cloudflare.com" >

[Eliminating Round trips using Preconnect](https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/)

**Comment by shierro** [comment]
Hi,

i also noticed the same thing, now it's even 13.6MB(seems like a SPA), loading big images that are not used on the landing page, w/c would be bad seo

<img width="1366" alt="screen shot 2019-01-09 at 8 11 51 pm" src="https://user-images.githubusercontent.com/12129589/50898766-13df1300-144b-11e9-8ffb-09790a20f43c.png">

Maybe lazy loading the images might help, or even optimizing it using [image optimizers](https://tinypng.com/)
